server:
  port: 8087
spring:
  profiles: test
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jiangyuyinggood/shunfeng-config.git
  application:
    name: config-8087-8087
---
spring:
  profiles:
    active: dev
---
server:
  port: 8087
spring:
  profiles: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jiangyuyinggood/shunfeng-config.git
  application:
    name: config-8087