eureka:
  client:
    service-url:
      defaultZone: http://eureka1.com:8082/eureka,http://eureka2.com:8083/eureka,http://eureka3.com:8084/eureka
  instance:
    instance-id: user-management-8080
    prefer-ip-address: true